# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/IdleISS

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
             - v1-dependencies-{{ checksum "requirements.txt" }}
             - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Make test directory
          command: mkdir -p test-reports/python/

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python3 setup.py nosetests --tests tests

      - store_artifacts:
          path: test-reports
          destination: test-reports
        
      - store_test_results:
          path: test-reports
